// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGqAKiuzTeK5LRAlzldWz_WgeL4mFQPI',
    appId: '1:131689649799:web:2494838c3c27352fd94a22',
    messagingSenderId: '131689649799',
    projectId: 'bible-ba4b7',
    authDomain: 'bible-ba4b7.firebaseapp.com',
    storageBucket: 'bible-ba4b7.firebasestorage.app',
    measurementId: 'G-13VMN7MGR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZFiUBbkVZ1bKsrpE6KAUOBn8Na3w0j7M',
    appId: '1:131689649799:android:6c0fb0c899ee1366d94a22',
    messagingSenderId: '131689649799',
    projectId: 'bible-ba4b7',
    storageBucket: 'bible-ba4b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkgrAOYLN_SHuvR9gJPkRqgmkGWXH9WsU',
    appId: '1:131689649799:ios:776ad208bb8f1c59d94a22',
    messagingSenderId: '131689649799',
    projectId: 'bible-ba4b7',
    storageBucket: 'bible-ba4b7.firebasestorage.app',
    iosBundleId: 'com.chama.bibleApp',
  );
}
